from . import user_crud
from . import user_role_crud
from . import manager_crud
from . import payroll_crud
from . import teacher_crud
from . import parent_crud
from . import student_crud
from . import subject_crud
from . import test_crud
from . import tuition_crud
from . import enrollment_crud
from . import class_crud
from . import attendance_crud
from . import evaluation_crud
from . import schedule_crud
from . import teacher_review_crud
from . import notification_crud
