from . import user_route
from . import manager_route
from . import payroll_route
from . import teacher_route
from . import parent_route
from . import student_route
from . import tuition_route
from . import class_route
from . import attendance_route
from . import schedule_route
from . import teacher_review_route
from . import notification_route
from . import register_route
from . import auth_route